import { format } from "date-fns";
import { AIArticle } from "@/lib/actions";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

type ArticlePostProps = {
  article: AIArticle;
};

export default function ArticlePost({ article }: ArticlePostProps) {
  const { fields } = article;

  return (
    <div className="space-y-4">
      <h1 className="text-3xl font-bold">{fields.title}</h1>
      <p className="text-sm text-muted-foreground">
        Generated by: {fields.model} | Created:{" "}
        {format(new Date(fields.createdTime), "MMMM d, yyyy")}
      </p>
      <div className="prose prose-lg max-w-none dark:prose-invert">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            a: ({ node, ...props }) => (
              <a {...props} target="_blank" rel="noopener noreferrer" />
            ),
          }}
        >
          {fields.content}
        </ReactMarkdown>
      </div>
    </div>
  );
}
